name: Server health check

on:
  schedule:
    - cron:  '40 6,18 * * *'

jobs:
  send_healthcheck_ping:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://pokedex-geaj.onrender.com/health
          max-attempts: 3
          retry-delay: 5s